apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: apps
 labels:
  tier: frontend
spec:
 replicas: 3
 selector:
  matchLabels:
   tier: frontend
 template:
  metadata:
   namespace: apps
   labels:
    tier: frontend
  spec:
   containers:
    - name: nginx-container
      image: nginx:1.14.2
      ports:
        - containerPort: 80
